package com.saga.be.entity.enums;

public enum NotificationType {
    COURSE_MEMBERSHIP_ADDED,
    MANUAL_ADMIN_BROADCAST,
    MANUAL_LECTURER_COURSE_BROADCAST,
    JIRA_LINK_SUCCEEDED,
    GITHUB_LINK_SUCCEEDED,
    JIRA_PROJECT_LINK_SUCCEEDED,
    GITHUB_PROJECT_LINK_SUCCEEDED,
    TASK_CREATED,
    TASK_UPDATED,
    TASK_ASSIGNEE_CHANGED,
    TASK_SPRINT_CHANGED,
    TASK_ESTIMATION_CHANGED,
    TASK_STATUS_CHANGED,
    TASK_DELETED,
    SPRINT_CREATED,
    SPRINT_UPDATED,
    SPRINT_STARTED,
    SPRINT_CLOSED,
    SPRINT_DELETED,
    TASK_DUE_TOMORROW,
    TASK_DUE_TODAY,
    TASK_OVERDUE
}
