# AWS Cognito issuer, for example:
# https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_xxxxxxxxx
spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO_ISSUER_URI}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
