spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

server.servlet.session.cookie.secure=${SESSION_COOKIE_SECURE:true}
server.servlet.session.cookie.same-site=${SESSION_COOKIE_SAME_SITE:none}

springdoc.api-docs.enabled=${SWAGGER_ENABLED:false}
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:false}
