spring.config.import=optional:file:.env[.properties]
spring.application.name=be
server.port=8080

# Gọi biến từ file .env
spring.datasource.url=${AIVEN_JDBC_URL}
spring.datasource.username=${AIVEN_DB_USERNAME}
spring.datasource.password=${AIVEN_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Tự động tạo bảng và hiện SQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect